"use client";

import { Artifact } from "@/lib/artifact";

import { MarkdownArtifact } from "./MarkdownArtifact";
import { SandboxedIframe } from "./SandboxedIframe";

interface ArtifactViewerProps {
  artifact?: Artifact | null;
  onClose?: () => void;
}

export function ArtifactViewer({
  artifact = null,
  onClose,
}: ArtifactViewerProps) {
  return (
    <aside
      aria-label="Artifact viewer"
      className="flex h-full min-h-0 flex-col bg-neutral-950"
    >
      <header className="flex shrink-0 items-center justify-between border-b border-neutral-800 px-4 py-3">
        <div className="flex min-w-0 items-center gap-3">
          <div
            aria-hidden="true"
            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-neutral-800 bg-neutral-900 text-neutral-400"
          >
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.7"
              className="h-4 w-4"
            >
              <path
                d="M6 3.75h8.25L18.5 8v12.25H6z"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M14 3.75V8h4.5M9 12h6M9 15.5h6"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>

          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-white">
                Artifact
              </h2>

              {artifact && (
                <span className="rounded-md border border-neutral-800 bg-neutral-900 px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wide text-neutral-500">
                  {artifact.type}
                </span>
              )}
            </div>

            <p className="mt-0.5 truncate text-xs text-neutral-600">
              {artifact?.title ?? "Generated content"}
            </p>
          </div>
        </div>

        {onClose && (
          <button
            type="button"
            onClick={onClose}
            aria-label="Close artifact viewer"
            title="Close artifact viewer"
            className="ml-4 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-neutral-800 text-neutral-500 transition hover:border-neutral-600 hover:bg-neutral-900 hover:text-white focus:outline-none focus:ring-2 focus:ring-neutral-700"
          >
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              className="h-4 w-4"
              aria-hidden="true"
            >
              <path
                d="M6 6l12 12M18 6L6 18"
                strokeLinecap="round"
              />
            </svg>
          </button>
        )}
      </header>

      <div className="min-h-0 flex-1 p-3">
        {!artifact ? (
          <div className="flex h-full items-center justify-center rounded-xl border border-dashed border-neutral-800">
            <div className="max-w-sm px-6 text-center">
              <div
                aria-hidden="true"
                className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl border border-neutral-800 bg-neutral-900 text-neutral-500"
              >
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  className="h-5 w-5"
                >
                  <path
                    d="M6 3.75h8.25L18.5 8v12.25H6z"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                  <path
                    d="M14 3.75V8h4.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </div>

              <h3 className="mt-4 text-sm font-semibold text-neutral-300">
                No artifact selected
              </h3>

              <p className="mt-2 text-xs leading-5 text-neutral-600">
                Select an artifact generated by an assistant
                response to view it here.
              </p>
            </div>
          </div>
        ) : artifact.type === "markdown" ? (
          <MarkdownArtifact content={artifact.content} />
        ) : (
          <SandboxedIframe
            content={artifact.content}
            title={artifact.title}
          />
        )}
      </div>
    </aside>
  );
}